@hostname=localhost
@port=5298
@host={{hostname}}:{{port}}
@controller=experiencias

@recursoId =1

GET http://{{host}}/api/{{controller}}/ HTTP/1.1
###

GET http://{{host}}/api/{{controller}}/{{recursoId}} HTTP/1.1
###

POST http://{{host}}/api/{{controller}}/ HTTP/1.1
Content-Type: application/json

{
  "numeroDocumento": null,
  "email": null,
  "telefone": null,
  "senha": null,
  "tipoPerfil": 0,
  "pretensaoSalarial": 0,
  "id": 0
}
###

PUT http://{{host}}/api/{{controller}}/{{recursoId}} HTTP/1.1
Content-Type: application/json
###

DELETE http://{{host}}/api/{{controller}}/{{recursoId}} HTTP/1.1
Content-Type: application/json
###
