@hostname=localhost
@port=5298
@host={{hostname}}:{{port}}
@controller=freelancers

@recursoId =2

GET http://{{host}}/api/{{controller}}/ HTTP/1.1
###

GET http://{{host}}/api/{{controller}}/{{recursoId}} HTTP/1.1
###

POST http://{{host}}/api/{{controller}}/ HTTP/1.1
Content-Type: application/json

{
  "numeroDocumento": "123.456.789-00",
  "nome": "Pedro",
  "dataNascimento": "2001-08-24T00:00:00.4001839-03:00",
  "email": "pedro@teste.com",
  "telefone": "(79)99999-8234",
  "senha": "Senha123!",
  "pretensaoSalarial": 5000
}
###

PUT http://{{host}}/api/{{controller}}/{{recursoId}} HTTP/1.1
Content-Type: application/json
###

DELETE http://{{host}}/api/{{controller}}/{{recursoId}} HTTP/1.1
Content-Type: application/json
###
